### ISSUE TITLE
Unable to access Syncthing Plugin Configuration settings[BUG] 

### ISSUE THREAD

**Issue by Tanzeel159** [LBF38/obsidian-syncthing-integration#94]
**Describe the bug**
I was using Syncthing before to sync Obsidian files. So I already have the software setup. When I installed the plugin it says Syncthing is not installed.

**To Reproduce**
1) Already setup syncthing software
2) Install syncthing plugin later
3) try accessing the configuration setting.

**Expected behavior**
Have access to the config settings where we can setup API keys and other important details.

**Screenshots**
![image](https://github.com/LBF38/obsidian-syncthing-integration/assets/20295349/3556a771-a51b-4284-adf6-d73f21c7af92)
![image](https://github.com/LBF38/obsidian-syncthing-integration/assets/20295349/56bea5d1-eace-4e6d-a5c2-25bf08133e94)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Brave Browser
 - Version: Obsidian - 1.4.3
 - 
**Additional context**
I have attached the log files as requested.

``
[obsidian.md-1692122113320.log](https://github.com/LBF38/obsidian-syncthing-integration/files/12347058/obsidian.md-1692122113320.log)

**Comment by LBF38** [comment]
Thank you for the report. I'm on it.

**Comment by brimwats** [comment]
Same here! 
![image](https://github.com/LBF38/obsidian-syncthing-integration/assets/73113656/527d6dc2-c44c-4f73-a40a-5d6d68fef890)

**Comment by LBF38** [comment]
Hi everyone, I have made some refactors in the settings tab and in the controllers.
I also have simplified some calls to the API for checking the Syncthing Status. Therefore, this should be working fine in the latest version of the plugin.
Please report any other bug if you find one. Or reopen this one if you still have the same error. (after updating the plugin plz).
Thanks !

PS: The Syncthing Configuration view isn't currently available in the settings tab as I'm refactoring it and should be available in the near future.

**Comment by Tanzeel159** [comment]
It's working fine now. I am able to access the api config page. I reinstalled syncthing from my side and have no error at the moment.

**Comment by imeed166** [comment]
Still have the same problem after the latest update, syncthing is running, i'm on mac os monterey.
![image](https://github.com/LBF38/obsidian-syncthing-integration/assets/38974541/9bbf8db1-7bff-466d-87b5-ef8a7b92b6c4)

**Comment by LBF38** [comment]
> Still have the same problem after the latest update, syncthing is running, i'm on mac os monterey. ![image](https://user-images.githubusercontent.com/38974541/261809083-9bbf8db1-7bff-466d-87b5-ef8a7b92b6c4.png)

Have you entered the api key ? Could you provide more information please ?
I don't have a MacOS so I can't test it. However, it should work fine if you have a working Syncthing instance.

**Comment by imeed166** [comment]
- I downloaded the [syncthing macos bundle](https://github.com/syncthing/syncthing-macos)
- I've tried the api key from syncthing settings, same result.
- I've tried using the plugin in a clean vault, same result.
- This is what I get when I click on "check API status" and "check CLI status"
![image](https://github.com/LBF38/obsidian-syncthing-integration/assets/38974541/38c74e6f-4054-41e3-9c05-382790fa2384)

**Comment by LBF38** [comment]
> * I downloaded the [syncthing macos bundle](https://github.com/syncthing/syncthing-macos)
> * I've tried the api key from syncthing settings, same result.
> * I've tried using the plugin in a clean vault, same result.
> * This is what I get when I click on "check API status" and "check CLI status"
>   ![image](https://user-images.githubusercontent.com/38974541/261851154-38c74e6f-4054-41e3-9c05-382790fa2384.png)

Okey, then no worries, it would be resolved in next release I think. I'm working on a refactor for the GUI / base Syncthing URL. 
Check the GUI address and enter the following : `http://localhost:8384`. And it should work. Or replace `localhost` with the ip address i.e. `127.0.0.1`.
Refer to https://github.com/LBF38/obsidian-syncthing-integration/issues/105#issuecomment-1685263406 for more info.

**Comment by imeed166** [comment]
I've tried what you described, but same results. I'll wait for the next release and try again. Let me know If you'd like me to comment on the other issue from now on.

**Comment by LBF38** [comment]
It should be resolved with the latest release. Otherwise, please tell me.

**Comment by imeed166** [comment]
Tried right now with the new release. This is what I get 
![image](https://github.com/LBF38/obsidian-syncthing-integration/assets/38974541/c0553b4f-6a57-401d-86fd-6e51742b43b2)

**Comment by LBF38** [comment]
Then, it works perfectly !
The plugin still doesn't have all Syncthing features, but the Ping/Pong tells you that everything is good. And the second message is that you don't have the CLI installed, which isn't a problem at all. It should work fine, as the syncthing controller of the plugin will test both.

**Comment by imeed166** [comment]
But it still have the message in red "syncthing is not found" and now, I reloaded the app, I can't get the "pong" again.

**Comment by imeed166** [comment]
and this what i get when I click on "open syncthing GUI"
![image](https://github.com/LBF38/obsidian-syncthing-integration/assets/38974541/cfabc01c-dc59-4b95-86fb-4a5148409939)

**Comment by imeed166** [comment]
And now I get, the pong again, I think it has to do with GUI credentials, I was trying to change them in syncthing's setting, I won't modify them again, to keep the connection.

**Comment by imeed166** [comment]
When I reloaded obsidian, the red message disappeared.

**Comment by LBF38** [comment]
> and this what i get when I click on "open syncthing GUI" ![image](https://user-images.githubusercontent.com/38974541/262484979-cfabc01c-dc59-4b95-86fb-4a5148409939.png)

Yeah, I know that, I also found it after the v2 release. All features aren't yet fully stable. I'm still actively working on those.

**Comment by LBF38** [comment]
> And now I get, the pong again, I think it has to do with GUI credentials, I was trying to change them in syncthing's setting, I won't modify them again, to keep the connection.

This error should be related to the Syncthing API Key I think. GUI credentials are only necessary for mobile support, while it is not fully working for now.
